# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: self  # Name of the self-hosted agent pool

steps:
- script: |
    echo Running Python script: num_sum.py
    python num_sum.py
  displayName: 'Run Python program'

- script: |
    echo Compiling and running Java program: num_sum.java
    java num_sum.java
  displayName: 'Run Java program'

- script: |
    echo Opening Webpage : Index.html
    start index.html
  displayName: 'Start HTML Page'